config/routes.rb
Ball::Application.routes.draw do

  get "home/index"

  devise_for :users

  resources :users, :only => [:show] do
    resources :meals, :only => [:edit, :update]
  end

  namespace :admin do 
	resources :users do
	 collection do
	  get 'summary'
         end
     end
  end 

  match 'home/' => 'home#index'
  match 'admin/' => 'admin/users#index'

  root :to => 'home#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  #attr_accessible :allergies, :coffee, :vegetarian, :wine
 
  belongs_to :user

  WINE = ["Red Wine","White Wine","No Wine Preference", "Soft Drink"]  

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :email, :name
  validates_uniqueness_of :email

  include ActiveModel::ForbiddenAttributesProtection

  has_one :meal, :dependent => :destroy 


  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,  :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :admin
  # attr_accessible :title, :body

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"

  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def index
	@users = User.where(:admin_only => :false)
        @admin_users = User.where(:admin => :true)
	respond_to do |format|
		format.html
	end
  end

  def show
       @user = User.find(params[:id])
       @meal = @user.meal
	respond_to do |format|
		format.html
	end
  end

  def new
	@user = User.new
	respond_to do |format|
		format.html
	end

  end

  def edit
	@user = User.find(params[:id])
	respond_to do |format|
		format.html
	end

  end

  def create
    password = Devise.friendly_token.first(10)
    @user = User.new(user_params)

    @user.password = password
    @user.build_meal
     
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
	UserMailer.welcome_email(@user,password).deliver
      else
        format.html { render action: "new" }
      end
    end
	
  end

  def update
	@user = User.find(params[:id])

         if @user.update_attributes(user_params)
            redirect_to admin_users_path, :notice => 'You have sucessfully added a guest.'
        else
          render :action => 'edit'
        end

  end

  def destroy
	@user = User.find(params[:id])
	@user.destroy

    	respond_to do |format|
      	  format.html { redirect_to admin_users_path }
    	end
  end

  def summary
	@users = User.includes(:meal).where(:admin_only => :false)

	@veg_count = Meal.where(:vegetarian => :true).count
	@guest_count = User.where(:admin_only => :false).count

        @chosen_count = Meal.where(:chosen => :true).count
        @coffee_count = Meal.where(:coffee => :true).count

	respond_to do |format|
      	  format.html
          format.pdf do
            pdf = SummaryFormPdf.new(@users, @veg_count, @guest_count, @coffee_count)
            send_data pdf.render, filename: "summary.pdf", type: "application/pdf", dispostion: "inline"
          end

          format.ods do
	   ods = SummaryFormOds.new(@users, @veg_count, @guest_count, @coffee_count)
	   ods.create_sheet
	   file = "#{Rails.root}/tmp/summary_#{Process.pid}";
	   if ods.write_file file
	     send_file file,  filename: "my-spreadsheet.ods", type: "application/ods", dispostion: "inline"
	   end
          end

    	end

  end

  private

  def authenticate_admin!
   unless current_user.admin
	redirect_to root_path, :alert => "You are not an admin go away"
   end
  end

  def user_params
       params.require(:user).permit(:name,:email,:admin, :admin_only)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private 

  def after_sign_in_path_for(resource_or_scope)
   user_path(current_user)
  end	
	
  def after_sign_out_path_for(resource_or_scope)
   root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
 before_filter :authenticate_user!
 before_filter :authenticate_access

 def edit
  @meal = current_user.meal

  respond_to do |format|
		format.html
  end

 end

 def update
  @meal = Meal.find params[:id]
  @meal.chosen = true

   if @meal.update_attributes(meal_params)
      UserMailer.update_meal(current_user).deliver
      redirect_to user_path(current_user), :notice => 'Your menu options were successfully updated.'
   else
      render :action => 'edit'
   end
 end


 private
 
 def meal_params
  params.require(:meal).permit(:vegetarian,:wine, :coffee, :allergies, :friends)
 end

 def authenticate_access
  user = User.find(params[:user_id])
  unless current_user == user 
   redirect_to root_path, :alert => "You are not permitted to access this page"
  end
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_access

  def show
    @user = User.includes(:meal).find(params[:id])
  end

 private 

  def authenticate_access
   user = User.find(params[:id])
   unless current_user == user 
    redirect_to root_path, :alert => "You are not permitted to access this page"
   end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
 def true_false_icon(status)
  if status
  return "<i class ='gen-enclosed foundicon-checkmark green'></i>".html_safe
  else
  return "<i class ='gen-enclosed foundicon-remove red'></i>".html_safe 
 end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_email_helper.rb
module MealsEmailHelper

 def vegetarian(vege)
   html = ""
   if vege
   html += "Vegetarian Menu"
   else
   html += "Standard Menu"
   end
   return html.html_safe
  
 end

 def coffee(cof)
   html = ""
   if cof
   html += "Yes Please"
   else
   html += "No Thanks"
   end
   return html.html_safe
 end

 def allergies(allergies)
   html = ""
   if allergies.empty?
   html += "None"
   else
   html += allergies
   end
   return html.html_safe
 end

 def friends(friends)
   html = ""
   if friends.empty?
   html += "None selected"
   else
   html += friends
   end
   return html.html_safe
 end




end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  .row        
    .large-4.columns
      = render :partial => "shared/alert_block"

  .row
    .large-4.small-6.columns
      = f.label :name
      = f.text_field :name

  .row
    .large-4.small-6.columns
      = f.label :email
      = f.text_field :email

  .row
    .large-4.small-6.columns
      = f.label :admin do
        = f.check_box :admin
        %span
          Admin

  .row
    .large-4.columns
      = f.label :admin_only do
        = f.check_box :admin_only
        %span
          Admin Only (Not a guest)

  .row
    .large-4.small-6.columns
      = f.submit "Add User", :class => "button"

app/views/admin/users/edit.html.haml
%h3 Edit Guest

= render 'form'

app/views/admin/users/index.html.haml
.row
  .large-4.columns
    = render :partial => "shared/alert_block"

.row
  .large-2.columns
    %i{:class => 'foundicon-edit'}
    = link_to 'Meal Summary', summary_admin_users_path
  .large-2.columns
    %i{:class => 'foundicon-page'}
    = link_to 'Meal Summary (pdf)', summary_admin_users_path(:format => :pdf)
  .large-2.columns
    %i{:class => 'foundicon-page'}
    = link_to 'Meal Summary (ods)', summary_admin_users_path(:format => :ods)
  .large-6.columns

.row
  .large-2.columns
    %i{:class => 'foundicon-plus'}
    = link_to 'Add User', new_admin_user_path
.row
  .large-12.small-12.columns
    %h5 Application Administrators
    %table
      %tr
        %th Name
        %th Email
      - @admin_users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to 'Show', admin_user_path(user)
          %td= link_to 'Edit', edit_admin_user_path(user)
          %td= link_to 'Destroy', admin_user_path(user), :confirm => 'Are you sure?', :method => :delete
   
.row
  .large-12.small-12.columns
    %h5 Guests
    %table
      %tr
        %th Name
        %th Email
        %th Chosen Meal
        %th
        %th
        %th
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td=  true_false_icon(user.meal.chosen)
          %td= link_to 'Show', admin_user_path(user)
          %td= link_to 'Edit', edit_admin_user_path(user)
          %td= link_to 'Destroy', admin_user_path(user), :confirm => 'Are you sure?', :method => :delete

app/views/admin/users/new.html.haml
.row
  .large-6.columns
    %h4 Add Guest

= render 'form'

.row
  .large-6.small-4.columns
    = link_to "Back", admin_users_path

app/views/admin/users/show.html.haml
.row
  .large-6.columns
    %h5 
      = @user.name
    %p 
      Email: 
      = @user.email
    %p 
      Admin: 
      = true_false_icon(@user.admin)

.row
  .large-6.columns
    %p 
      Admin only (not a guest): 
      = true_false_icon(@user.admin_only)


- if @user.meal.chosen #|| @user.admin_only
  .row
    .large-6.columns
      %h6 Menu
      %p 
        Vegetarian:
        =  true_false_icon(@meal.vegetarian)
      %p 
        Coffee:
        =  true_false_icon(@meal.coffee)
      %p 
        Wine:
        = @meal.wine
      %p 
        Allergies:
        = @meal.allergies
      %p
        Friends:
        = @meal.friends
- else
  .row
    .large-6.columns
      %p
        Meal not chosen

.row
  .large-6.columns
    = link_to "Back", admin_users_path

app/views/admin/users/summary.html.haml
.row
  .large-12.columns  
    %h5 Meals Summary

.row
  .large-12.columns  
    %table
      %tr
        %th 
        %th Name
        %th Chosen
        %th Vegetarian
        %th Coffee
        %th Wine
        %th Allergies
        %th Friends
      - @users.each do |user|
        %tr
          %td
          %td= user.name
          %td= true_false_icon(user.meal.chosen)
          %td= true_false_icon(user.meal.vegetarian)
          %td= true_false_icon(user.meal.coffee)
          %td= user.meal.wine
          %td= user.meal.allergies
          %td= user.meal.friends
      %tr
        %td Totals
        %td= @guest_count
        %td= @chosen_count
        %td= @veg_count
        %td= @coffee_count
        %td
        %td
        %td
.row
  .large-6.columns
    = link_to "Back", admin_users_path

app/views/home/index.html.haml
= render "shared/header_mast"
= render "shared/alert_block"

.row
  .small-10.large-6.columns
    %p 
      %b The Astbury Society invites you to attend a black tie  event:
.row
  .small-10.large-6.columns
    %p 
      %b Venue: 
      The Park Plaza Hotel
.row
  .small-10.large-6.columns
    %p 
      %b Date: 
      10th May 2013
    %p 
      %b Time: 
      7:00pm
.row
  .small-10.large-6.columns
    %p 
      %b Price: 
      £30
.row
  .small-10.large-6.columns
    %p Evening includes: a three course meal, half a bottle of wine or soft drink and entertainment.
.row
  .small-10.large-6.columns
    %p Buy tickets from your nearest society member:

.people
  .row
    =render :partial => "shared/rep", :locals => { :image => "megan.png", :name => "Megan"}
    =render :partial => "shared/rep", :locals => { :image => "sasha.png", :name => "Sasha"}
    =render :partial => "shared/rep", :locals => { :image => "jenny.png", :name => "Jenny"}
    =render :partial => "shared/rep", :locals => { :image => "joe.png", :name => "Joe"}
  .row
    =render :partial => "shared/rep", :locals => { :image => "sophie.png", :name => "Sophie"}
    =render :partial => "shared/rep", :locals => { :image => "kat.png", :name => "Kat"}
    =render :partial => "shared/rep", :locals => { :image => "rachel.png", :name => "Rachel"}
    =render :partial => "shared/rep", :locals => { :image => "ivona.png", :name => "Ivona"}
  .row
    =render :partial => "shared/rep", :locals => { :image => "pete.png", :name => "Pete"}
    =render :partial => "shared/rep", :locals => { :image => "claire.png", :name => "Claire"}
    =render :partial => "shared/rep", :locals => { :image => "valeria.png", :name => "Valeria"}
    .small-6.large-3.columns
 

app/views/layouts/admin.html.haml
!!!
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]

  %head
    %meta{ :charset => "utf-8" }

    -# Uncomment to make IE8 render like IE7
    -# meta http-equiv="X-UA-Compatible" content="IE=7"

    -# Set the viewport width to device width for mobile
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %link{:href=>'http://fonts.googleapis.com/css?family=Cinzel+Decorative:700', :rel=> 'stylesheet', :type=> 'text/css'}

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tag

  %body
    .row
      .small-12.large-12.columns
        = render :partial => "shared/admin_header_mast"
        = yield


    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!!
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]

  %head
    %meta{ :charset => "utf-8" }

    -# Uncomment to make IE8 render like IE7
    -# meta http-equiv="X-UA-Compatible" content="IE=7"

    -# Set the viewport width to device width for mobile
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %link{:href=>'http://fonts.googleapis.com/css?family=Cinzel+Decorative:700', :rel=> 'stylesheet', :type=> 'text/css'}

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tag

  %body
    #container.plain.row
      .small-12.large-12.columns
        = yield

    %footer.row
      .large-12.columns
        .row
          .large-6.columns
            %p Website by Jonathan Bramble
    

    = javascript_include_tag "application"

app/views/layouts/home.html.haml
!!!
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]

  %head
    %meta{ :charset => "utf-8" }

    -# Uncomment to make IE8 render like IE7
    -# meta http-equiv="X-UA-Compatible" content="IE=7"

    -# Set the viewport width to device width for mobile
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %link{:href=>'http://fonts.googleapis.com/css?family=Cinzel+Decorative:700', :rel=> 'stylesheet', :type=> 'text/css'}

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tag

  %body
    #container.pretty.row
      .small-12.large-12.columns
        = yield

    %footer.row
      .large-12.columns
        .row
          .large-6.columns
            %p Website by Jonathan Bramble
    

    = javascript_include_tag "application"

app/views/meals/_form.html.haml
%h3 Menu Choices
= form_for [current_user, @meal] do |m|
  .row
    .large-6.small-8.columns.small-vgap
      %label{:for => "meal_vegetarian"}
        = m.check_box :vegetarian
        Vegetarian Option - select if required

  .row
    .large-6.small-6.columns.small-vgap
      %label
        Choice of Drink 
        %span *subject to availability 
      = m.collection_select :wine, Meal::WINE, :to_s, :to_s, {}, { :class =>"medium" }

  .row
    .large-6.small-8.columns.small-vgap
      =m.label :coffee do
        = m.check_box :coffee
        Coffee - select if required
  
  .row
    .large-6.small-8.columns.small-vgap
      %label
        Allergies/Intolerances
      = m.text_area :allergies

  .row
    .large-6.small-8.columns.small-vgap
      %label
        Friends
        %span -for seating plans enter the names of friends you would like to sit with
      = m.text_area :friends

  .row
    .large-6.columns
      = m.submit "Submit Choices" ,:class=>"button inline"

app/views/meals/edit.html.haml
= render "shared/header_mast"
= render "shared/menu"

.row
  .large-offset-1.large-11.columns.menu-form
    = render 'form'

app/views/shared/_admin_header_mast.html.haml
.row
  .small-8.large-6.columns
    %h1 Admin Area
  .large-offset-4.small-offset-0.large-2.small-4.columns
    .sign-in
      = render :partial => "shared/user_links"
      %p
        = link_to "Home", home_path	

app/views/shared/_admin_links.html.haml
- if current_user && current_user.admin
  |
  %a
    = link_to "Admin", admin_users_path

app/views/shared/_alert_block.html.haml
= content_tag(:div, flash[:error], :id => "flash_error", :class=>"alert-box alert") if flash[:error] 
= content_tag(:div, flash[:notice], :id => "flash_notice", :class=>"alert-box success") if flash[:notice]
= content_tag(:div, flash[:alert], :id => "flash_alert", :class=>"alert-box alert") if flash[:alert]

app/views/shared/_header_mast.html.haml
=content_for :title do
  Astbury Ball 2013

.row
  .small-8.large-6.columns
    %h1 Astbury May Ball
  .large-offset-4.small-offset-0.large-2.small-4.columns
    .sign-in
      = render :partial => "shared/user_links"
      = render :partial => "shared/admin_links"

app/views/shared/_menu.html.haml
.menu
  .row     
    .large-4.large-offset-1.small-8.small-offset-1.columns.menu-choice
      %h3 Menu
      %h5 Starter
      %p Duck and orange parfait with kumquat chilli jam and red chard salad
      %h5 Main
      %p Garlic and rosemary studded lamb rump with fondant potato and red wine jus
      %h5 Dessert
      %p Sticky toffee pudding with fudge sauce
    .large-4.large-offset-1.small-8.small-offset-1.columns.menu-choice
      %h3 Vegetarian Menu
      %h5 Starter
      %p Sweet tomato and red pepper soup with basil oil
      %h5 Main
      %p Mediterranean vegetable wellington with rosemary and feta cheese
      %h5 Dessert
      %p Sticky toffee pudding with fudge sauce
    .large-2.columns

app/views/shared/_rep.html.haml
.small-6.large-3.columns
  .panel.rep
    =image_tag(image,:class=>"img")
    %div
      %p 
        = name

app/views/shared/_user_links.html.haml
- unless current_user
  = link_to "Sign in", new_user_session_path
- else
  = link_to current_user.name, user_path(current_user), :class => "user_name"
  = link_to "Sign out", destroy_user_session_path, :method=>:delete


 

app/views/users/show.html.haml
= render :partial => "shared/header_mast"

.row
  .small-10.large-6.columns
    %p 
      Hello 
      = @user.name

.row
  .small-10.large-6.columns
    - if @user.meal.chosen
      = link_to "Edit your menu choices", edit_user_meal_path(@user), :class => "button"
    - else
      = link_to "Enter your menu choices", edit_user_meal_path(@user), :class => "button"